### ISSUE TITLE
Create a QuizList.txt for the user

### ISSUE THREAD

**Issue by henrikmdev** [geordzNZ/Quizzer#1]
https://github.com/geordzNZ/Quizzer/blob/9ece91e3eec985203b3fe588d62f06c05f683ed5/Quizzer/Program.cs#L20

There's an issue where if I don't have the QuizList.txt file, I can't run your program. I had to comment this out temporarily to create the file through your program.

**Comment by geordzNZ** [comment]
Made it check if the file exists before doing that.
Also updated Listing actions to check if Quizzes exist before displaying 'noting'
