### ISSUE TITLE
Don't use public static variables to store your program state

### ISSUE THREAD

**Issue by incredibleLeitman** [geordzNZ/Quizzer#11]
https://github.com/geordzNZ/Quizzer/blob/d057e2f7c8d57a45c3b303f4326d6e3f90b8868b/Quizzer/Program.cs#L12
This is very hard to keep track of when your data gets modified.
Also this means that it could get changed from everywhere in your code easily which produces lot of errors if you are not careful or  are not aware how your program is structured

**Comment by geordzNZ** [comment]
What is the better way to do it then?
To me the QuizList needs to be available everywhere as it is used everywhere, for the Quizzer to use and the Editor to amend / add.

I guess ... as I have now removed the FileExists checks out of Program then QuizList could exist in each mode as it would be refreshed at each entry into that particular mode...

**Comment by incredibleLeitman** [comment]
The way to go would be to either have a separate variable for the quiz creation and playing,
or a common variable for both cases if you need it in each mode


The important thing is thought, that this data, that is essential for your programm is not accessed from "outside",
meaning statements like "Program.QuizList = ..." or "Program.QuizList.AnyFunction" should not be used.
The reason is, that this can be placed *anywhere* in your code, modifying essential data and during runtime you have *no idea* when and how this was changed. 
Instead you should rely on providing access by passing it to functions and getting it as return value

**Comment by incredibleLeitman** [comment]
Just as additional info, those two line
```List<Quiz> editorQuizList = new List<Quiz>();
editorQuizList = UtilitiesLogic.ReadFromQuizFile();```
can also be combined into one:
```List<Quiz> editorQuizList = UtilitiesLogic.ReadFromQuizFile();```

which is not also a little bit clearer to read,
but spares one additional memory allocation

**Comment by geordzNZ** [comment]
ahh yeah of course .. done.
