### ISSUE TITLE
User named file

### ISSUE THREAD

**Issue by henrikmdev** [geordzNZ/Quizzer#2]
https://github.com/geordzNZ/Quizzer/blob/9ece91e3eec985203b3fe588d62f06c05f683ed5/Quizzer/Objects/Quiz.cs#L24

Minor thing. But it looks like you don't let the user have full control over the filename for the quiz he or she creates?

**Comment by geordzNZ** [comment]
That was by design. I wanted to not worry the user about the file name and create it for them.
Also making sure they dont specify any chars in the filename that windows doesnt like :\$% etc ....

**Comment by geordzNZ** [comment]
ignore this commit, associated with the wrong issue

**Comment by geordzNZ** [comment]
thinking about this further, I should make the FileName private instead of public
